services:
  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      SERVER_URL: "http://localhost:11435/v1/audio/speech" # put your openai speech endpoint here
      VOICES: alloy,echo,fable,onyx,nova,shimmer
      MODELS: tts-1-hd,tts-1
    command: ["python", "app.py"]